{******************************** HELP **************************************}
{‘œ ˜¬«¦ «¦ unit ¬§˜¨®¦¬¤ ¦  ¡à› ¡¦  ˜§¦ «¦ ˜¨®œ ¦ george.txt.‡˜ §¨œ§œ  ¤˜   }
{š ¤œ  compile ¡˜  ¤˜ «¦§¦Ÿœ«žŸœ  ©˜¤ unit ©«¦ ¡¬¨ àª §¨¦š¨˜££˜.             }
{                                                                            }
{George Papaioannou Thessaloniki 1994   (c) Digital ToolWorks     !!!        }
{****************************************************************************}


UNIT TopicHelp;

INTERFACE

Const

  { * The constants that added from the Original Help Text * }

         HelpFileName =     'george.Hlp';


              hcIndex =     0;
              hcTopic =     1;
         hcCalculator =     2;
             hcPazzle =     3;



IMPLEMENTATION

End.
