{******************************** HELP **************************************}
{‘œ ˜¬«¦ «¦ unit ¬§˜¨®¦¬¤ ¦  ¡à› ¡¦  ˜§¦ «¦ ˜¨®œ ¦ dhm.txt.‡˜ §¨œ§œ  ¤˜   }
{š ¤œ  compile ¡˜  ¤˜ «¦§¦Ÿœ«žŸœ  ©˜¤ unit ©«¦ ¡¬¨ àª §¨¦š¨˜££˜.             }
{                                                                            }
{George Papaioannou Thessaloniki 1996   (c) Digital ToolWorks  Ver 3.00   !! }
{****************************************************************************}


UNIT TopicHlp;

INTERFACE

Const

  { * The constants that added from the Original Help Text * }

         HelpFileName =     'dhm.Hlp';


            hcDeskTop =     0;
          hcMouseFunc =     1;
       hcKeyboardFunc =     2;
            hcMoveWin =     3;
           hcErrorMsg =     4;
           hcGlossary =     5;



IMPLEMENTATION

End.
